import { Rackets } from "./schema";

export const dataRackets: Rackets = [
  {
    id: 1,
    brand: "Yonex",
    name: "Astrox 100 ZZ",
    slug: "astrox-100-zz",
    weight: "3U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    brand: "Victor",
    name: "Thruster Ryuga II",
    slug: "thruster-ryuga-ii",
    weight: "4U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    brand: "Li-Ning",
    name: "BladeX 900",
    slug: "bladex-900",
    weight: "2U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    brand: "Hundred",
    name: "Nitrix Volta 70",
    slug: "nitrix-volta-70",
    weight: "5U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    brand: "Apacs",
    name: "Ziggler LHI Pro III",
    slug: "ziggler-lhi-pro-iii",
    weight: "3U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    brand: "Yonex",
    name: "Voltage Z-Force II LCW Limited",
    slug: "voltage-z-force-ii-lcw-limited",
    weight: "3U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    brand: "Felet",
    name: "Woven 1000",
    slug: "woven-1000",
    weight: "4U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
