import { Rackets } from "./schema";

export const dataRackets: Rackets = [
  {
    id: 1,
    brand: "Yonex",
    name: "Astrox 100 ZZ",
    slug: "astrox",
    weight: "3U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    brand: "Victor",
    name: "Thruster Ryuga II",
    slug: "thruster",
    weight: "4U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    brand: "Li-Ning",
    name: "BladeX 900",
    slug: "bladex",
    weight: "2U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    brand: "Hundred",
    name: "Nitrix Volta 70",
    slug: "nitrix",
    weight: "5U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    brand: "Apacs",
    name: "Ziggler LHI Pro III",
    slug: "ziggler",
    weight: "3U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    brand: "Yonex",
    name: "Voltage Z-Force II LCW Limited",
    slug: "voltage",
    weight: "3U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    brand: "Felet",
    name: "Woven 1000",
    slug: "woven",
    weight: "4U",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
